<a href="https://colab.research.google.com/github/AryanJadhao/Pytorch/blob/main/pytorch_nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

# **method 1**

In [10]:
# create model class ------> method 1
class Model(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
      out = self.linear(features)
      out = self.sigmoid(out)
      return out

In [11]:
# create dataset
features = torch.rand(10,5)

# create model object
model = Model(features.shape[1])

# forward pass
model(features)

tensor([[0.4596],
        [0.4058],
        [0.4974],
        [0.4083],
        [0.4255],
        [0.4121],
        [0.4935],
        [0.3932],
        [0.4445],
        [0.4242]], grad_fn=<SigmoidBackward0>)

**1 hidden layer (3 neurons)**

In [12]:
# create model class ------> method 1
class Model(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()

    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
      out = self.linear1(features)
      out = self.relu(out)
      out = self.linear2(out)
      out = self.sigmoid(out)
      return out

In [13]:
# create dataset
features = torch.rand(10,5)

# create model object
model = Model(features.shape[1])

# forward pass
model(features)

tensor([[0.5416],
        [0.5399],
        [0.5399],
        [0.5399],
        [0.5399],
        [0.5399],
        [0.5407],
        [0.5484],
        [0.5399],
        [0.5416]], grad_fn=<SigmoidBackward0>)

# **method 2** **using container Sequential**

In [18]:
# create model class ------> method 2
class Model(nn.Module):
  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3,1),
      nn.Sigmoid()
    )

  def forward(self, features):
    return self.network(features)

In [19]:
# create dataset
features = torch.rand(10,5)

# create model object
model = Model(features.shape[1])

# forward pass
model(features)

tensor([[0.4511],
        [0.4679],
        [0.4546],
        [0.4541],
        [0.4516],
        [0.4498],
        [0.4537],
        [0.4522],
        [0.4537],
        [0.4511]], grad_fn=<SigmoidBackward0>)