<a href="https://colab.research.google.com/github/AryanJadhao/Pytorch/blob/main/simpleNN_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [2]:
df = pd.read_csv("/content/breast-cancer.csv")
df.head(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [5]:
df.shape

(569, 32)

In [8]:
df.drop(columns='id', inplace=True)

In [9]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [10]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [11]:
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.transform(x_test)

In [12]:
x_train


array([[-0.2252985 , -0.50161757, -0.28963887, ..., -0.25805081,
        -0.65532785, -0.42463473],
       [-0.92845566, -1.43334294, -0.9730825 , ..., -1.14727327,
        -0.28642636, -0.39089854],
       [ 0.81608614, -0.09312714,  0.77689517, ...,  0.52819269,
        -0.17193969, -0.63956692],
       ...,
       [-0.49528712,  0.59533987, -0.49518907, ...,  0.11037463,
         0.08565532,  0.46665369],
       [ 1.94351112,  0.67336614,  1.87143919, ...,  1.22093194,
        -0.01452052, -1.381219  ],
       [-0.44188277, -0.26065412, -0.51070229, ..., -1.50731129,
        -1.08942314, -1.56840045]])

In [13]:
y_train

224    B
159    B
167    M
29     M
378    B
      ..
284    B
105    M
88     B
210    M
360    B
Name: diagnosis, Length: 455, dtype: object

In [14]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [15]:
y_train

array([0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,

# **Numpy arrays ----> pytorch tensors**

In [16]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [17]:
x_train_tensor.shape

torch.Size([455, 30])

In [45]:
class mysimpleNN():
  def __init__(self, X):
    self.weights = torch.rand(X.shape[1], 1, dtype=torch.float64, requires_grad=True)
    self.bias = torch.zeros(1,dtype=torch.float64, requires_grad=True)

  def forward(self, X):
    z = torch.matmul(X, self.weights)+self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    loss = -(y_train_tensor * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1-y_pred)).mean()
    return loss

In [49]:
learning_rate = 0.1
epochs = 25

# **Training Pipeline**

In [28]:
model = mysimpleNN(x_train_tensor)
model.weights

tensor([[0.4596],
        [0.1461],
        [0.7416],
        [0.6336],
        [0.5913],
        [0.1324],
        [0.5427],
        [0.2391],
        [0.6258],
        [0.2607],
        [0.1767],
        [0.3344],
        [0.8362],
        [0.3144],
        [0.7138],
        [0.5052],
        [0.8466],
        [0.2524],
        [0.6900],
        [0.0529],
        [0.9180],
        [0.4290],
        [0.9547],
        [0.9573],
        [0.0418],
        [0.4547],
        [0.2917],
        [0.9138],
        [0.3507],
        [0.7355]], dtype=torch.float64, requires_grad=True)

In [21]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [52]:
# create model
model = mysimpleNN(x_train_tensor)

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model.forward(x_train_tensor)

  # loss calculation
  loss = model.loss_function(y_pred, y_train_tensor)


  # backward pass
  loss.backward()

  # parameters update
  with torch.no_grad():
    model.weights -= learning_rate * model.weights.grad
    model.bias -= learning_rate * model.bias.grad

  # zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  # print loss in every epochs
  print(f"epochs: {epoch+1}, loss: {loss.item()}")

epochs: 1, loss: 3.4349408167908675
epochs: 2, loss: 3.2980864504624545
epochs: 3, loss: 3.152652151838906
epochs: 4, loss: 3.0027256881913074
epochs: 5, loss: 2.8498426952346803
epochs: 6, loss: 2.69434271259638
epochs: 7, loss: 2.5339427537876134
epochs: 8, loss: 2.366178056190545
epochs: 9, loss: 2.202564333247673
epochs: 10, loss: 2.039896499346286
epochs: 11, loss: 1.8775445490098488
epochs: 12, loss: 1.7217875790928634
epochs: 13, loss: 1.575112057013338
epochs: 14, loss: 1.4318140757333637
epochs: 15, loss: 1.2975235692934515
epochs: 16, loss: 1.1795874675385494
epochs: 17, loss: 1.0794352968521765
epochs: 18, loss: 0.9975791927769926
epochs: 19, loss: 0.9332698799931902
epochs: 20, loss: 0.8844900918857951
epochs: 21, loss: 0.8483693067740562
epochs: 22, loss: 0.8218265717256744
epochs: 23, loss: 0.8021191174274988
epochs: 24, loss: 0.787110750353926
epochs: 25, loss: 0.7752860953618861


# **Evaluation**

In [56]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()

  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"accuracy: {accuracy}")


accuracy: 0.6292705535888672
