In [126]:
import pandas as pd
import numpy as np
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

In [127]:
df = pd.read_csv("/content/breast-cancer.csv")
df.head(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  radius_worst  texture_worst  perimeter_worst  area_worst  \
0  ...         25.38          17.33           184.60      2019.0   
1  ...         24.99          23.41           158.80      1956.0   
2  ...         23.57          25.53           152.50      1709.0   
3  ...         14.91          26.50            98.87       567.7   
4  ...         22.54          16.67           152.20      1575.0   

   smoothness_worst  compactness_worst  concavity_worst  concave points_worst  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   symmetry_worst  fractal_dimension_worst  
0          0.4601                  0.11890  
1          0.2750                  0.08902  
2          0.3613                  0.08758  
3          0.6638                  0.17300  
4          0.2364                  0.07678  

[5 rows x 32 columns]

In [128]:
df.shape

(569, 32)

In [129]:
df.drop(columns='id', inplace=True)

In [130]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [131]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,1:], df.iloc[:,0], test_size=0.2)

In [132]:
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.transform(x_test)

In [133]:
x_train

array([[ 1.18464945e-01,  2.36579034e-01,  1.31007387e-01, ...,
         1.07776687e+00,  3.04025720e+00,  8.75934169e-01],
       [ 1.27622061e+00, -3.71932635e-01,  1.24967862e+00, ...,
         8.10530829e-01, -6.35713293e-01,  5.14865190e-01],
       [ 2.64617269e-01, -1.58406212e-02,  2.36991159e-01, ...,
         5.44821849e-01,  1.05052942e-01,  1.98910864e-03],
       ...,
       [-1.28087191e+00, -7.34785890e-01, -1.29935628e+00, ...,
        -6.26130139e-01, -2.30914045e-01, -1.52980643e-01],
       [-7.81374851e-01, -2.93631028e-02, -8.15753159e-01, ...,
        -6.65986486e-01, -8.15988261e-01, -9.63145635e-01],
       [-8.12897902e-01,  2.29875747e+00, -8.62903419e-01, ...,
        -1.72897511e+00, -2.18280030e+00, -1.35109712e+00]])

In [134]:
y_train

199    M
498    M
291    B
103    B
285    B
      ..
8      M
226    B
234    B
67     B
561    B
Name: diagnosis, Length: 455, dtype: object

In [135]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [136]:
y_train

array([1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0,

# **Numpy arrays ----> pytorch tensors**

In [137]:
x_train_tensor = torch.from_numpy(x_train)
x_test_tensor = torch.from_numpy(x_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [149]:
x_train_tensor = x_train_tensor.float()
x_test_tensor = x_test_tensor.float()
y_train_tensor = y_train_tensor.float()
y_test_tensor = y_test_tensor.float()

In [138]:
x_train_tensor.shape

torch.Size([455, 30])

In [139]:
y_train_tensor.dtype

torch.int64

In [154]:
import torch.nn as nn

class mySimpleNN(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)
    return out

In [156]:
# define loss function
loss_function = nn.BCELoss()

In [141]:
learning_rate = 0.1
epochs = 25

# **Training Pipeline**

In [143]:
model = mySimpleNN(x_train_tensor.shape[1])
model.linear.weight

Parameter containing:
tensor([[-0.1560,  0.0393,  0.1763,  0.1792, -0.0942,  0.1531,  0.1065, -0.0234,
          0.0574,  0.0851, -0.0172, -0.0750,  0.0517, -0.0377, -0.0264, -0.1217,
         -0.0112,  0.0806, -0.1162,  0.1550,  0.1654,  0.0923,  0.1536,  0.1628,
         -0.1565, -0.0660,  0.0215,  0.0483, -0.1710, -0.0044]],
       requires_grad=True)

In [144]:
model.linear.bias

Parameter containing:
tensor([-0.0638], requires_grad=True)

In [148]:
y_train_tensor.to(torch.float32).dtype

torch.float32

In [165]:
# create model
model = mySimpleNN(x_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=0.1)

# define loop
for epoch in range(epochs):
  # forward pass
  y_pred = model(x_train_tensor)

  # loss calculation
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # zero gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in every epochs
  print(f"epochs: {epoch+1}, loss: {loss.item()}")

epochs: 1, loss: 0.8279547095298767
epochs: 2, loss: 0.5983962416648865
epochs: 3, loss: 0.480884850025177
epochs: 4, loss: 0.41436880826950073
epochs: 5, loss: 0.3712679445743561
epochs: 6, loss: 0.3404443860054016
epochs: 7, loss: 0.31690436601638794
epochs: 8, loss: 0.2981027364730835
epochs: 9, loss: 0.28259551525115967
epochs: 10, loss: 0.2694939374923706
epochs: 11, loss: 0.25821664929389954
epochs: 12, loss: 0.24836485087871552
epochs: 13, loss: 0.23965409398078918
epochs: 14, loss: 0.23187536001205444
epochs: 15, loss: 0.22487080097198486
epochs: 16, loss: 0.21851865947246552
epochs: 17, loss: 0.21272313594818115
epochs: 18, loss: 0.2074076533317566
epochs: 19, loss: 0.20251008868217468
epochs: 20, loss: 0.19797943532466888
epochs: 21, loss: 0.19377319514751434
epochs: 22, loss: 0.18985575437545776
epochs: 23, loss: 0.18619687855243683
epochs: 24, loss: 0.1827707588672638
epochs: 25, loss: 0.1795550286769867


# **Evaluation**

In [166]:
with torch.no_grad():
  y_pred = model.forward(x_test_tensor)
  y_pred = (y_pred > 0.9).float()

  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"accuracy: {accuracy}")


accuracy: 0.5344721674919128


# **USING NN-MODULE**