In [2]:
import torch
print(torch.__version__)

2.9.0+cpu


In [3]:
if torch.cuda.is_available():
  print(f"GPU is available : {torch.cuda.get_device_name(0)}")
else:
  print("using CPU")

using CPU


# **CREATING** **TENSOR**

In [4]:
# USING EMPTY
h = torch.empty(2,3)

In [5]:
type(h)

torch.Tensor

In [6]:
# USING ZEROS
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# USING ONES
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# USING RAND
torch.rand(2,3)

tensor([[0.4421, 0.4133, 0.1688],
        [0.4022, 0.7767, 0.6209]])

In [9]:
# USE OF MANUAL SEED -->   WILL GET THE SAME VALUES AFTER MULTIPLE USE OF RAND
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [11]:
# USING TENSORS
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [12]:
# arange
print("using arange : ", torch.arange(0,10,2))

# linspace
print("using linspace : ", torch.linspace(0,10,5))

# eye
print("using eye : ", torch.eye(5))

# full
print("using full : ", torch.full((3,3),5))

using arange :  tensor([0, 2, 4, 6, 8])
using linspace :  tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
using eye :  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full :  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# **TENSOR SHAPES**

In [13]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
x.shape

torch.Size([2, 3])

In [15]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 1, 0]])

In [16]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [17]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [18]:
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

# **TENSOR** **DATATYPES**

In [19]:
x.dtype

torch.int64

In [20]:
torch.tensor([[1.0,2.0,3.0],[4.0,5.0,6.0]], dtype=torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [21]:
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

In [22]:
torch.rand_like(x.to(torch.float64))

tensor([[0.1015, 0.6642, 0.9736],
        [0.6941, 0.3464, 0.9751]], dtype=torch.float64)

# **MATHEMATICAL OPERATION**

**1.** **SCALAR** **OPS**

In [23]:
x = torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [24]:
# addition
print("addition : ", x+2)

# subtraction
print("subtraction : ", x-2)

# multiplication
print("multiplication : ", x*2)

# division
print("division : ", x/2)

# int division
print("Int division : ", (x*100) // 2)

# mod
print("mod : ", ((x*100) // 2) % 2)

# power
print("power : ", x**2)

addition :  tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])
subtraction :  tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])
multiplication :  tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])
division :  tensor([[0.1119, 0.1512],
        [0.0892, 0.4119]])
Int division :  tensor([[11., 15.],
        [ 8., 41.]])
mod :  tensor([[1., 1.],
        [0., 1.]])
power :  tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])


**2. ELEMENT WISE OPS**

In [25]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [26]:
# add
print("addition : ",a + b)

# sub
print("sub : ",a - b)

# mul
print("mul : ",a * b)

# div
print("div : ",a / b)

# mod
print("mod : ",a % b)

# floor div
print("floor div : ",a // b)

# exp
print("exp : ",a ** b)

addition :  tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])
sub :  tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])
mul :  tensor([[0.1348, 0.6842, 0.2343],
        [0.2343, 0.5888, 0.2072]])
div :  tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])
mod :  tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])
floor div :  tensor([[2., 1., 0.],
        [3., 0., 1.]])
exp :  tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])


In [27]:
c = torch.tensor([1,-2,-3,4,-5])

In [28]:
# absosute value
torch.abs(c)

tensor([1, 2, 3, 4, 5])

In [29]:
# negative value
torch.neg(c)

tensor([-1,  2,  3, -4,  5])

In [30]:
d = torch.tensor([1.9,2.1,3.7,1.4,5.3])

In [31]:
# round
torch.round(d)

tensor([2., 2., 4., 1., 5.])

In [33]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 2., 6.])

In [34]:
# floor
torch.floor(d)

tensor([1., 2., 3., 1., 5.])

In [35]:
# clamp
torch.clamp(d, min=2, max=4)

tensor([2.0000, 2.1000, 3.7000, 2.0000, 4.0000])

**3. REDUCTION OPS**

In [37]:
e = torch.randint(size=(2,3), low=0, high=10)
e

tensor([[5, 7, 5],
        [9, 9, 7]])

In [38]:
# sum
torch.sum(e)

tensor(42)

In [39]:
# sum along column
torch.sum(e, dim=0)

tensor([14, 16, 12])

In [40]:
# sum along rows
torch.sum(e, dim=1)

tensor([17, 25])

In [44]:
# mean
# torch.mean(e) --> error

torch.mean(e.to(torch.float32))

# do it for rows and columns just give dimensions

# similarly median

tensor(7.)

In [45]:
# similarly used to calculate prod, standard deviation (std), variance (var), argmax, argmin

**4.MATRIX OPS**

In [47]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=1, high=5)

print(f)
print(g)

tensor([[5, 9, 8],
        [9, 7, 9]])
tensor([[1, 3],
        [2, 2],
        [3, 4]])


In [48]:
# matrix multiplication
torch.matmul(f,g)

tensor([[47, 65],
        [50, 77]])

In [50]:
# dot product
vec1 = torch.tensor([1,2,3])
vec2 = torch.tensor([4,5,6])
torch.dot(vec1,vec2)

tensor(32)

In [51]:
# transpose
# 0 -----> 1
torch.transpose(f,0,1)

tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [53]:
# determinant
p = torch.randint(size=(3,3), low=0,  high=10, dtype=torch.float32)
torch.det(p)

tensor(-20.0000)

**5. COMPARISON OPS**

In [54]:
s = torch.randint(size=(2,3), low=0,  high=10, dtype=torch.float32)
t = torch.randint(size=(2,3), low=0,  high=10, dtype=torch.float32)

print(s)
print(t)

tensor([[3., 3., 5.],
        [0., 6., 4.]])
tensor([[0., 8., 4.],
        [7., 2., 3.]])


In [55]:
# greater than
print(s>t)

# less than
print(s<t)

# equal to
print(s == t)

# less than equal to , greater than equal to

tensor([[ True, False,  True],
        [False,  True,  True]])
tensor([[False,  True, False],
        [ True, False, False]])
tensor([[False, False, False],
        [False, False, False]])


**6. SPECIAL FUNCTIONS**

In [57]:
k = torch.randint(size=(2,3), low=0, high=10)
k

tensor([[0, 4, 2],
        [7, 1, 1]])

In [58]:
# log
torch.log(k)

tensor([[  -inf, 1.3863, 0.6931],
        [1.9459, 0.0000, 0.0000]])

In [59]:
# exp
torch.exp(k)

tensor([[1.0000e+00, 5.4598e+01, 7.3891e+00],
        [1.0966e+03, 2.7183e+00, 2.7183e+00]])

In [60]:
# sqrt
torch.sqrt(k)

tensor([[0.0000, 2.0000, 1.4142],
        [2.6458, 1.0000, 1.0000]])

In [62]:
# sigmoid
torch.sigmoid(k)

tensor([[0.5000, 0.9820, 0.8808],
        [0.9991, 0.7311, 0.7311]])

In [65]:
# softmax
# torch.softmax(k,dim=0) ----> error

torch.softmax(k.to(torch.float32), dim=0)

# similarly relu

tensor([[9.1105e-04, 9.5257e-01, 7.3106e-01],
        [9.9909e-01, 4.7426e-02, 2.6894e-01]])

# **INPLACE OPERATIONS**

In [66]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2243, 0.8935, 0.0497],
        [0.1780, 0.3011, 0.1893]])
tensor([[0.9186, 0.2131, 0.3957],
        [0.6017, 0.4234, 0.5224]])


In [67]:
# m+n ----> m
m.add_(n)

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [68]:
m

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

In [69]:
# relu(m) ----> m
m.relu_()

tensor([[1.1429, 1.1066, 0.4454],
        [0.7796, 0.7245, 0.7117]])

# **COPYING A TENSOR**

In [70]:
a = torch.rand(2,3)
a

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [71]:
b = a

In [72]:
b

tensor([[0.4175, 0.0340, 0.9157],
        [0.3079, 0.6269, 0.8277]])

In [73]:
# but
print("id of a : ",id(a))
print("id of b : ", id(b))

id of a :  134992771063136
id of b :  134992771063136


In [74]:
# hence change in one may change other

In [75]:
b = a.clone()

In [76]:
print("id of a : ",id(a))
print("id of b : ", id(b))

id of a :  134992771063136
id of b :  134992771008624


# **TENSOR OPS ON GPU**

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
device = torch.device('cuda')

In [4]:
# creating a new tensor on GPU
torch.rand((2,3), device=device)

tensor([[0.7826, 0.0326, 0.0384],
        [0.1697, 0.8957, 0.0944]], device='cuda:0')

In [8]:
# moving existing tensor to GPU
a = torch.rand(2,3)
a

b = a.to(device)
b

tensor([[0.2585, 0.1190, 0.6052],
        [0.3208, 0.3484, 0.5108]], device='cuda:0')

# **RESHAPING TENSORS**

In [10]:
a = torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [11]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [12]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
# unsqueeze
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [17]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])